export const POST_REQUEST = "POST_REQUEST";
export const POST_SUCCESS = "POST_SUCCESS";
export const POST_FAIL = "POST_FAIL";

export const SINGLE_POST_REQUEST = "SINGLE_POST_REQUEST";
export const SINGLE_POST_SUCCESS = "SINGLE_POST_SUCCESS";
export const SINGLE_POST_FAIL = "SINGLE_POST_FAIL";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";

export const GET_COMMENTS_FOR_POST_REQUEST = "GET_COMMENTS_FOR_POST_REQUEST";
export const GET_COMMENTS_FOR_POST_SUCCESS = "GET_COMMENTS_FOR_POST_SUCCESS";
export const GET_COMMENTS_FOR_POST_FAIL = "GET_COMMENTS_FOR_POST_FAIL";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL";

export const UPDATE_PHOTO_POST_REQUEST = "UPDATE_PHOTO_POST_REQUEST";
export const UPDATE_PHOTO_POST_SUCCESS = "UPDATE_PHOTO_POST_SUCCESS";
export const UPDATE_PHOTO_POST_FAIL = "UPDATE_PHOTO_POST_FAIL";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const TOGGLE_LIKE_REQUEST = "TOGGLE_LIKE_REQUEST";
export const TOGGLE_LIKE_SUCCESS = "TOGGLE_LIKE_SUCCESS";
export const TOGGLE_LIKE_FAIL = "TOGGLE_LIKE_FAIL";
